<br>
<p>Гибкое сравнение в PHP</p>
    <table class="comparisons1">
        <tr><th></th><th>true</th><th>false</th><th>1</th><th>0</th><th>-1</th><th>"1"</th><th>null</th><th>"PHP"</th></tr>         
        <tr><td>true</td><td><?php var_dump (true == true);?></td><td><?php var_dump (true == false);?></td><td><?php var_dump (true == 1);?></td><td><?php var_dump (true == 0);?></td><td><?php var_dump (true == -1);?></td><td><?php var_dump (true == "1");?></td><td><?php var_dump (true == null);?></td><td><?php var_dump (true == "PHP");?></td></tr>
        <tr><td>false</td><td><?php var_dump(false == true);?></td><td><?php var_dump (false == false);?></td><td><?php var_dump (false == 1);?></td><td><?php var_dump (false == 0);?></td><td><?php var_dump (false == -1);?></td><td><?php var_dump (false == "1");?></td><td><?php var_dump (false == null);?></td><td><?php var_dump (false == "PHP");?></td></tr>
        <tr><td>1</td><td><?php var_dump (1 == true);?></td><td><?php var_dump (1 == false);?></td><td><?php var_dump (1 == 1);?></td><td><?php var_dump (1 == 0);?></td><td><?php var_dump (1 == -1);?></td><td><?php var_dump (1 == "1");?></td><td><?php var_dump (1 == null);?></td><td><?php var_dump (1 == "PHP");?></td></tr>
        <tr><td>0</td><td><?php var_dump (0 == true);?></td><td><?php var_dump (0 == false);?></td><td><?php var_dump (0 == 1);?></td><td><?php var_dump (0 == 0);?></td><td><?php var_dump (0 == -1);?></td><td><?php var_dump (0 == "1");?></td><td><?php var_dump (0 == null);?></td><td><?php var_dump (0 == "PHP");?></td></tr>
        <tr><td>-1</td><td><?php var_dump (-1 == true);?></td><td><?php var_dump (-1 == false);?></td><td><?php var_dump (-1 == 1);?></td><td><?php var_dump (-1 == 0);?></td><td><?php var_dump (-1 == -1);?></td><td><?php var_dump (-1 == "1");?></td><td><?php var_dump (-1 == null);?></td><td><?php var_dump (-1 == "PHP");?></td></tr>
        <tr><td>"1"</td><td><?php var_dump ("1" == true);?></td><td><?php var_dump ("1" == false);?></td><td><?php var_dump ("1" == 1);?></td><td><?php var_dump ("1" == 0);?></td><td><?php var_dump ("1" == -1);?></td><td><?php var_dump ("1" == "1");?></td><td><?php var_dump ("1" == null);?></td><td><?php var_dump ("1" == "PHP");?></td></tr>
        <tr><td>null</td><td><?php var_dump (null == true);?></td><td><?php var_dump (null == false);?></td><td><?php var_dump (null == 1);?></td><td><?php var_dump (null == 0);?></td><td><?php var_dump (null == -1);?></td><td><?php var_dump (null == "1");?></td><td><?php var_dump (null == null);?></td><td><?php var_dump (null == "PHP");?></td></tr>
        <tr><td>"PHP"</td><td><?php var_dump ("PHP" == true);?></td><td><?php var_dump ("PHP" == false);?></td><td><?php var_dump ("PHP" == 1);?></td><td><?php var_dump ("PHP" == 0);?></td><td><?php var_dump ("PHP" == -1);?></td><td><?php var_dump ("PHP" == "1");?></td><td><?php var_dump ("PHP" == null);?></td><td><?php var_dump ("PHP" == "PHP");?></td></tr>
    </table> 
    <br>
    <p>Жёсткое сравнение в PHP</p>
    <table class="comparisons2">
        <tr><th></th><th>true</th><th>false</th><th>1</th><th>0</th><th>-1</th><th>"1"</th><th>null</th><th>"PHP"</th></tr>         
        <tr><td>true</td><td><?php var_dump (true === true);?></td><td><?php var_dump (true === false);?></td><td><?php var_dump (true === 1);?></td><td><?php var_dump (true === 0);?></td><td><?php var_dump (true === -1);?></td><td><?php var_dump (true === "1");?></td><td><?php var_dump (true === null);?></td><td><?php var_dump (true === "PHP");?></td></tr>
        <tr><td>false</td><td><?php var_dump(false === true);?></td><td><?php var_dump (false === false);?></td><td><?php var_dump (false === 1);?></td><td><?php var_dump (false === 0);?></td><td><?php var_dump (false === -1);?></td><td><?php var_dump (false === "1");?></td><td><?php var_dump (false === null);?></td><td><?php var_dump (false === "PHP");?></td></tr>
        <tr><td>1</td><td><?php var_dump (1 === true);?></td><td><?php var_dump (1 === false);?></td><td><?php var_dump (1 === 1);?></td><td><?php var_dump (1 === 0);?></td><td><?php var_dump (1 === -1);?></td><td><?php var_dump (1 === "1");?></td><td><?php var_dump (1 === null);?></td><td><?php var_dump (1 === "PHP");?></td></tr>
        <tr><td>0</td><td><?php var_dump (0 === true);?></td><td><?php var_dump (0 === false);?></td><td><?php var_dump (0 === 1);?></td><td><?php var_dump (0 === 0);?></td><td><?php var_dump (0 === -1);?></td><td><?php var_dump (0 === "1");?></td><td><?php var_dump (0 === null);?></td><td><?php var_dump (0 === "PHP");?></td></tr>
        <tr><td>-1</td><td><?php var_dump (-1 === true);?></td><td><?php var_dump (-1 === false);?></td><td><?php var_dump (-1 === 1);?></td><td><?php var_dump (-1 === 0);?></td><td><?php var_dump (-1 === -1);?></td><td><?php var_dump (-1 === "1");?></td><td><?php var_dump (-1 === null);?></td><td><?php var_dump (-1 === "PHP");?></td></tr>
        <tr><td>"1"</td><td><?php var_dump ("1" === true);?></td><td><?php var_dump ("1" === false);?></td><td><?php var_dump ("1" === 1);?></td><td><?php var_dump ("1" === 0);?></td><td><?php var_dump ("1" === -1);?></td><td><?php var_dump ("1" === "1");?></td><td><?php var_dump ("1" === null);?></td><td><?php var_dump ("1" === "PHP");?></td></tr>
        <tr><td>null</td><td><?php var_dump (null === true);?></td><td><?php var_dump (null === false);?></td><td><?php var_dump (null === 1);?></td><td><?php var_dump (null === 0);?></td><td><?php var_dump (null === -1);?></td><td><?php var_dump (null === "1");?></td><td><?php var_dump (null === null);?></td><td><?php var_dump (null === "PHP");?></td></tr>
        <tr><td>"PHP"</td><td><?php var_dump ("PHP" === true);?></td><td><?php var_dump ("PHP" === false);?></td><td><?php var_dump ("PHP" === 1);?></td><td><?php var_dump ("PHP" === 0);?></td><td><?php var_dump ("PHP" === -1);?></td><td><?php var_dump ("PHP" === "1");?></td><td><?php var_dump ("PHP" === null);?></td><td><?php var_dump ("PHP" === "PHP");?></td></tr>
    </table> 